# Generated by Django 5.2.5 on 2025-08-29 10:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('category', models.CharField(choices=[('payment', 'Payment Issue'), ('delivery', 'Delivery Issue'), ('record', 'Record Quality or Condition Issue'), ('feedback', 'Feedback & Complaints'), ('other', 'Other')], default='payment', max_length=50)),
                ('description', models.TextField(help_text='Please let us know how we can help you.')),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Resolved')], default='open', max_length=10)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
