# Generated by Django 5.2.5 on 2025-09-06 11:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_alter_newslettersubscriber_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
