# Generated by Django 5.2.5 on 2025-09-02 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stripe_pid',
            field=models.CharField(default='', editable=False),
            preserve_default=False,
        ),
    ]
