# Generated by Django 5.2.5 on 2025-08-11 11:17

import cloudinary.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(1)])),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('image_url', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('debut_year', models.PositiveIntegerField(blank=True, null=True)),
                ('bio', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
