# Generated by Django 5.2.5 on 2025-08-11 11:37

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='image_url',
            field=cloudinary.models.CloudinaryField(default='default-artist_fw2mea', max_length=255, verbose_name='image'),
        ),
    ]
