# Generated by Django 5.2.5 on 2025-08-11 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_alter_artist_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='image_url',
            new_name='image',
        ),
    ]
