# Generated by Django 5.2.5 on 2025-08-12 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
