# Generated by Django 5.2.5 on 2025-08-12 11:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_alter_genre_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(1)])),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('size', models.CharField(choices=[('7"', '7 Inch'), ('10"', '10 Inch'), ('12"', '12 Inch')], max_length=10)),
                ('rpm', models.CharField(choices=[('33', '33RPM'), ('45', '45RPM'), ('78', '78RPM')], max_length=10)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('quantity', models.PositiveIntegerField()),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records_by_artist', to='records.artist')),
                ('genre', models.ManyToManyField(blank=True, related_name='records_by_genre', to='records.genre')),
            ],
        ),
    ]
