# Generated by Django 5.2.5 on 2025-08-12 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
