# Generated by Django 5.2.5 on 2025-08-12 11:57

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_record_release_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(default='default-record_rjj3wh', max_length=255, verbose_name='image')),
                ('image_type', models.CharField(choices=[('Front Cover', 'Front Cover'), ('Back Cover', 'Back Cover'), ('Disk', 'Disk'), ('Insert/Leaflet', 'Insert/Leaflet'), ('Other', 'Other')], default='Front Cover', max_length=50)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='records.record')),
            ],
        ),
    ]
