# Generated by Django 5.2.5 on 2025-08-19 10:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0008_recordimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='release_date',
        ),
        migrations.AddField(
            model_name='record',
            name='release_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)]),
        ),
        migrations.AlterField(
            model_name='artist',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
