# Generated by Django 5.2.5 on 2025-08-19 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0009_remove_record_release_date_record_release_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='description',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
