# Generated by Django 5.2.5 on 2025-08-30 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0013_alter_genre_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='hidden',
            field=models.BooleanField(default=True),
        ),
    ]
