# Generated by Django 5.2.5 on 2025-08-30 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0014_record_hidden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='slug',
            field=models.SlugField(blank=True, help_text='Slug will automatically generate if left blank.', max_length=100, unique=True),
        ),
    ]
