# Generated by Django 5.2.5 on 2025-09-03 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0015_alter_record_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='slug',
            field=models.SlugField(blank=True, help_text='This will be created automatically if left blank.', max_length=100, unique=True),
        ),
    ]
